-- RentBook root 접속
CREATE DATABASE rentBookDB;
USE rentBookDB;

CREATE TABLE tbl_BOOKS (
	B_CODE	VARCHAR(13)	NOT NULL	PRIMARY KEY,
	B_NAME	VARCHAR(125)	NOT NULL	,
	B_AUTHER	VARCHAR(125)	NOT NULL,	
	B_COMP	VARCHAR(125)		,
	B_YEAR	INT	NOT NULL	,
	B_IPRICE	INT		,
	B_RPRICE	INT	NOT NULL	
);
DESC tbl_books;
DROP TABLE tbl_books;
SHOW TABLES;
DESC tbl_books;

INSERT INTO tbl_books (
	B_CODE,B_NAME,B_AUTHER,B_COMP,B_YEAR,B_IPRICE,B_RPRICE
) VALUES (
	'001','자바야 놀자','야놀자','놀자출판사',2010,20000,2000
);
SELECT * FROM tbl_books;
